MID changes in reference app
Mastercard/credit-analytics-reference-app pull request #8
Opened 2024-09-20 12:02 UTC by AbhiramE151859

2024-09-23 05:13 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
>      public static List<Match> throwsNoMatchFound() throws UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException, ApiException {
can we have throwsNoMatchFoundByMID() method as well?

2024-09-23 05:13 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +                "AUS",// this must be USA_COUNTRY_CODE for the current release of the API
change comment to "this must be one of the ISO standard country codes supported by SBCA application"

2024-09-23 05:13 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    public static List<Match> throwsInvalidIDType() throws UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException, ApiException {
pass some invalid id type for this case like "MID" in place of empty

2024-09-23 05:13 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +                EXAMPLE_ID_VALUE
add throwsInvalidIDValue() example as well

2024-09-23 05:13 UTC, niduramurali commented on src/main/resources/small-business-credit-analytics.yaml
> +    CountryCodeNotPermittedExample:
we can remove this example. I think we are not having this test case either.

2024-09-23 05:13 UTC, niduramurali commented on src/main/resources/small-business-credit-analytics.yaml
> +    CountryCodeNotPermitted:
remove this example

2024-09-23 05:13 UTC, niduramurali commented on src/main/resources/small-business-credit-analytics.yaml
> +          - 'MERCHANT_ID'
do we need to maintain enum? This validation is taken care by SBCA Matches API.

2024-09-24 09:12 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    public static List<Match> getMultipleMatchByMID() throws UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException, ApiException {
change this to getMultipleMatch**es**ByMID

2024-09-24 09:21 UTC, niduramurali commented on src/main/resources/small-business-credit-analytics.yaml
>          pattern: '^[0-9A-Z]+'
on state_province_region can you remove this regex validation?

2024-09-24 09:21 UTC, niduramurali commented on src/main/resources/small-business-credit-analytics.yaml
>          pattern: '^[0-9A-Z- ]+'
remove regex on postal_code

2024-09-24 09:22 UTC, niduramurali commented on src/main/resources/small-business-credit-analytics.yaml
>        example: Fancy Restaurant
can we update this example value to single match results?

2024-09-24 09:23 UTC, niduramurali commented on src/main/resources/small-business-credit-analytics.yaml
>          pattern: '^[A-Z]+'
remove the regex on country_code. Let customers experience error messages from SBCA Matching API

2024-09-24 09:34 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    public static List<Match> getMultipleMatchByMID() throws UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException, ApiException {
change this to reflect plural getMultipleMatch**es**ByMID

2024-09-29 22:33 UTC, srinivasa-t requested changes
@AbhiramE151859 I have reviewed and added comments.

2024-09-29 22:33 UTC, srinivasa-t commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
@AbhiramE151859 why do we need to pass null for ID type and ID value when searching by name and address, why do we need have an overloaded method.
FYI @niduramurali

2024-09-29 22:33 UTC, srinivasa-t commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    }
@AbhiramE151859 why do we need to pass null for name and address fields  when searching by ID, why do we not have have an overloaded method.
FYI @niduramurali

2024-10-15 16:36 UTC, merged