RSA-681: added Monthly Metrics Reference App changes
Mastercard/credit-analytics-reference-app pull request #9
Opened 2024-11-22 12:52 UTC by Maithrie168505

Added metrics frequency parameter to the code changes.

2024-11-22 13:41 UTC, niduramurali requested changes
Changes looks good. We need answers for a few code changes.

2024-11-22 13:41 UTC, niduramurali commented on src/main/resources/small-business-credit-analytics.yaml
> +        month:
Do we need this month and week attributes?

2024-11-22 13:41 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> -                UUID.fromString(MERCHANT_NOT_FOUND_LOCATION_ID),
why did we update existing location_id to null?

2024-11-22 13:41 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> -                false,
why did we update consent from false to null?

2024-11-22 13:41 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +                "monthly",
use the constant defined at class level

2024-11-22 13:41 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    public static MetricsPerLocation getFullyPopulatedMetricsForMonthly() throws UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException, ApiExceptio
refactor this method name to getFullyPopulatedMonthlyMetrics

2024-11-22 13:41 UTC, niduramurali commented on src/test/java/com/mastercard/creditanalytics/api/MetricsApiTest.java
> +       Assert.assertNotNull(ApiExamples.getFullyPopulatedMetrics());
refactor existing metrics methods name to include weekly like getFullyPopulatedWeeklyMetrics

2024-11-25 04:19 UTC, niduramurali requested changes

2024-11-25 04:19 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> -                false,
We don't need to prioritize code coverage here. This call needs to be made with consent as 'false' since it talks about ConsentNotProvided error.

2024-11-25 04:19 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> -                UUID.fromString(MERCHANT_NOT_FOUND_LOCATION_ID),
Need to retain Merchant Not Found Location Id and null is not supposed to be used in this case

2024-11-25 04:19 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    public static MetricsPerLocation getFullyPopulatedWeeklyMetrics() throws UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException, ApiException {
Add Weekly word to all the existing methods like this one.

2024-11-25 04:19 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    public static MetricsPerLocation getFullyPopulateMonthlyMetrics() throws UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException, ApiException {
I think we need to add Monthly RSA Metrics cases for all the 4 location ids

2024-11-25 09:25 UTC, AbhiramE151859 commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    private static final String MONTHLY = "Monthly";
The word here should be "monthly". And same goes for weekly, it should be "weekly".

2024-11-25 11:30 UTC, niduramurali commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    private static final String MONTHLY = "Monthly";
It is case-insensitive, so can be "monthly" or "Monthly"

2024-11-25 12:40 UTC, AbhiramE151859 commented on src/main/java/com/mastercard/creditanalytics/api/ApiExamples.java
> +    private static final String MONTHLY = "Monthly";
ooh okay okay, great.

2024-12-03 09:50 UTC, merged